"""
Pydantic v2 schemas for LLM structured output in the Agentropolis agent pipeline.

These models are used as `output_schema` in Railtracks agent nodes, ensuring
that all LLM responses are validated before being persisted.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


def _make_strict(schema: dict) -> dict:
    """Mark the JSON schema as strict for OpenAI structured output."""
    schema["additionalProperties"] = False
    return schema


class ActionParams(BaseModel):
    """Structured action parameters. All fields optional — fill what's relevant."""

    location: str | None = None
    target: str | None = None
    detail: str | None = None


class ArchetypeAction(BaseModel):
    """A single action decided by the archetype agent for this tick."""

    action_type: Literal[
        "work",
        "commute",
        "eat",
        "sleep",
        "shop",
        "exercise",
        "socialize",
        "post",
        "attend_event",
        "visit_family",
    ]
    action_params: ActionParams
    duration: float = Field(description="Duration in hours")
    thinking: str = Field(description="1 sentence max", max_length=200)


class ArchetypeResponse(BaseModel):
    """Full response from the archetype (Tier 1) agent for one tick."""

    actions: list[ArchetypeAction]
    tweet: str | None = None


class FollowerVariation(BaseModel):
    """Per-follower variation generated by the Tier 2 agent."""
    model_config = ConfigDict(json_schema_extra=_make_strict)
    follower_id: int
    happiness_delta: float = Field(ge=-0.2, le=0.2)
    tweet_text: str | None = None
    position: list[float] | None = None  # [lat, lng] override


class FollowerVariationBatch(BaseModel):
    """Batch of follower variations returned by the Tier 2 agent."""

    variations: list[FollowerVariation]
