"""
Pydantic v2 schemas for LLM structured output in the Agentropolis agent pipeline.

These models are used as `output_schema` in Railtracks agent nodes, ensuring
that all LLM responses are validated before being persisted.

All models include `_make_strict` via `json_schema_extra` to satisfy OpenAI's
strict structured output requirements:
  - Every property listed in `required` (nullable fields use anyOf with null)
  - `additionalProperties: false` on every object
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


def _make_strict(schema: dict[str, Any]) -> None:
    """Post-process a Pydantic JSON schema for OpenAI strict structured output.

    OpenAI strict mode requires:
      1. All properties listed under `required` (nullable fields still appear
         as ``anyOf: [{type: X}, {type: null}]`` — they just must be present).
      2. ``additionalProperties: false`` on every object.

    Called in-place by Pydantic when ``json_schema_extra`` is a callable.
    """
    if "properties" in schema:
        schema["required"] = list(schema["properties"].keys())
    schema["additionalProperties"] = False


class ActionParams(BaseModel):
    """Structured action parameters. All fields optional — fill what's relevant."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    location: str | None = None
    target: str | None = None
    detail: str | None = None


class ArchetypeAction(BaseModel):
    """A single action decided by the archetype agent for this tick."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    action_type: Literal[
        "work",
        "commute",
        "eat",
        "sleep",
        "shop",
        "exercise",
        "socialize",
        "post",
        "attend_event",
        "visit_family",
    ]
    action_params: ActionParams = Field(default_factory=ActionParams)
    duration: float = Field(description="Duration in hours")
    thinking: str = Field(max_length=200, description="1 sentence max")


class ArchetypeResponse(BaseModel):
    """Full response from the archetype (Tier 1) agent for one tick."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    actions: list[ArchetypeAction]
    tweet: str | None = None


class FollowerVariation(BaseModel):
    """Per-follower variation generated by the Tier 2 agent."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    follower_id: int
    happiness_delta: float = Field(default=0.0, ge=-0.2, le=0.2)
    timing_offset_minutes: int = Field(default=0, ge=-15, le=15)
    tweet_text: str | None = None
    position: list[float] | None = None  # [lat, lng] override


class FollowerVariationBatch(BaseModel):
    """Batch of follower variations returned by the Tier 2 agent."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    variations: list[FollowerVariation]


class FollowerTweet(BaseModel):
    """Tweet generated for one follower by the tweet agent."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    follower_id: int
    tweet_text: str


class TweetBatch(BaseModel):
    """Batch of tweets returned by the tweet agent."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    tweets: list[FollowerTweet]
