"""
Pydantic v2 schemas for LLM structured output in the Agentropolis agent pipeline.

These models are used as `output_schema` in Railtracks agent nodes, ensuring
that all LLM responses are validated before being persisted.

All models include `_make_strict` via `json_schema_extra` to satisfy OpenAI's
strict structured output requirements:
  - Every property listed in `required` (nullable fields use anyOf with null)
  - `additionalProperties: false` on every object
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


def _make_strict(schema: dict[str, Any]) -> None:
    """Post-process a Pydantic JSON schema for OpenAI strict structured output.

    OpenAI strict mode requires:
      1. All properties listed under `required` (nullable fields still appear
         as ``anyOf: [{type: X}, {type: null}]`` — they just must be present).
      2. ``additionalProperties: false`` on every object.

    Called in-place by Pydantic when ``json_schema_extra`` is a callable.
    """
    if "properties" in schema:
        schema["required"] = list(schema["properties"].keys())
    schema["additionalProperties"] = False


class ActionParams(BaseModel):
    """Structured action parameters. All fields optional — fill what's relevant."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    location: str | None = None
    target: str | None = None
    detail: str | None = None


class ArchetypeAction(BaseModel):
    """A single action decided by the archetype agent for this tick."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    action_type: Literal[
        "work",
        "commute",
        "eat",
        "sleep",
        "shop",
        "exercise",
        "socialize",
        "post",
        "attend_event",
        "visit_family",
    ]
    action_params: ActionParams = Field(default_factory=ActionParams)
    duration: float = Field(description="Duration in hours")
    thinking: str = Field(max_length=200, description="1 sentence max")


class ArchetypeResponse(BaseModel):
    """Full response from the archetype (Tier 1) agent for one tick."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    actions: list[ArchetypeAction]
    tweet: str | None = None


class FollowerVariation(BaseModel):
    """Per-follower variation generated by the Tier 2 agent."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    follower_id: int
    happiness_delta: float = Field(default=0.0, ge=-0.2, le=0.2)
    timing_offset_minutes: int = Field(default=0, ge=-15, le=15)
    tweet_text: str | None = None
    position: list[float] | None = None  # [lat, lng] override


class FollowerVariationBatch(BaseModel):
    """Batch of follower variations returned by the Tier 2 agent."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    variations: list[FollowerVariation]


class FollowerTweet(BaseModel):
    """Tweet generated for one follower by the tweet agent."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    follower_id: int
    tweet_text: str


class TweetBatch(BaseModel):
    """Batch of tweets returned by the tweet agent."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    tweets: list[FollowerTweet]


# ---------------------------------------------------------------------------
# Event designer agent output
# ---------------------------------------------------------------------------


class GatheringZone(BaseModel):
    """A zone that attracts people during an event."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    zone_name: str = Field(description="Must match a valid work district or neighborhood name")
    pull_strength: float = Field(ge=0.0, le=1.0, description="Fraction of population drawn here")
    start_hour: int = Field(default=9, ge=0, le=23, description="Hour gathering starts (0-23). Protests 9, celebrations 14, festivals 10, emergencies 0")
    end_hour: int = Field(default=16, ge=0, le=23, description="Hour gathering ends (0-23). Can wrap past midnight (start=20 end=2). Rallies 16, parties 23, emergencies 23")


class IndustryEffect(BaseModel):
    """An effect targeting a specific industry."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    industry: str = Field(description="Must match a valid industry name")
    value: float = Field(description="The effect value for this industry")


class EventEffects(BaseModel):
    """Structured mechanical effects generated by the event designer agent."""

    model_config = ConfigDict(json_schema_extra=_make_strict)

    stay_home_rate: float | None = Field(default=None, ge=0.0, le=1.0, description="Override stay-home fraction (0.0-1.0)")
    happiness_delta: float | None = Field(default=None, ge=-0.3, le=0.3, description="Global per-tick happiness modifier")
    happiness_per_industry: list[IndustryEffect] | None = Field(default=None, description="Per-industry happiness modifiers")
    tweet_rate_multiplier: float | None = Field(default=None, ge=1.0, le=5.0, description="Multiplier on base 10% tweet rate")
    tweet_sentiment: str | None = Field(default=None, description="One-word mood hint for tweets")
    disease_transmission_multiplier: float | None = Field(default=None, ge=0.1, le=10.0, description="Multiplier on disease spread")
    gathering_zones: list[GatheringZone] | None = Field(default=None, description="Zones that attract people")
    industry_stay_home: list[IndustryEffect] | None = Field(default=None, description="Per-industry stay-home overrides")
    duration_ticks: int | None = Field(default=None, ge=1, description="How many hourly ticks this event lasts")
    reasoning: str = Field(description="1-2 sentence explanation of effect choices")
