"""initial schema v2

Revision ID: cc6e82843068
Revises: 
Create Date: 2026-03-14 13:36:00.678265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc6e82843068'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('virtual_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='paused', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('archetypes',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=False),
    sa.Column('social_class', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'archetype_id')
    )
    op.create_table('companies',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'company_id')
    )
    op.create_table('demographics',
    sa.Column('demographic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('is_company', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('social_class', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('demographic_id')
    )
    op.create_table('events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_prompt', sa.Text(), nullable=False),
    sa.Column('virtual_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'event_id')
    )
    op.create_index('idx_events_session_time', 'events', ['session_id', 'virtual_time'], unique=False)
    op.create_table('memories',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('virtual_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('action_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('thinking', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'memory_id')
    )
    op.create_index('idx_memories_agent_time', 'memories', ['session_id', 'archetype_id', 'virtual_time'], unique=False)
    op.create_table('posts',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('virtual_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'post_id')
    )
    op.create_index('idx_posts_session_time', 'posts', ['session_id', 'virtual_time'], unique=False)
    op.create_table('relationships',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('follower1_id', sa.Integer(), nullable=False),
    sa.Column('follower2_id', sa.Integer(), nullable=False),
    sa.Column('relation_strength', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.CheckConstraint("relation_type IN ('employee', 'employer', 'married', 'friends', 'enemies', 'family', 'coworker')", name='ck_relationships_relation_type'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'relation_id')
    )
    op.create_index('idx_relationships_f1', 'relationships', ['session_id', 'follower1_id'], unique=False)
    op.create_index('idx_relationships_f2', 'relationships', ['session_id', 'follower2_id'], unique=False)
    op.create_table('followers',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('race', sa.String(length=64), nullable=True),
    sa.Column('home_position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('work_position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status_ailments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('happiness', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id', 'archetype_id'], ['archetypes.session_id', 'archetypes.archetype_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'follower_id')
    )
    op.create_index('idx_followers_archetype', 'followers', ['session_id', 'archetype_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_followers_archetype', table_name='followers')
    op.drop_table('followers')
    op.drop_index('idx_relationships_f2', table_name='relationships')
    op.drop_index('idx_relationships_f1', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index('idx_posts_session_time', table_name='posts')
    op.drop_table('posts')
    op.drop_index('idx_memories_agent_time', table_name='memories')
    op.drop_table('memories')
    op.drop_index('idx_events_session_time', table_name='events')
    op.drop_table('events')
    op.drop_table('demographics')
    op.drop_table('companies')
    op.drop_table('archetypes')
    op.drop_table('sessions')
    op.drop_table('locations')
    # ### end Alembic commands ###
